# Generated by Django 5.0.3 on 2024-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=300)),
                ('Summery', models.TextField()),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Up_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
