# Generated by Django 5.0.3 on 2024-12-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='addblog',
            name='Up_time',
        ),
    ]
