# Generated by Django 4.2.18 on 2025-01-25 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_App', '0002_remove_addblog_time_remove_addblog_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='Image',
            field=models.ImageField(default=1, upload_to='Blogs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addblog',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='addblog',
            name='Up_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
