# Generated by Django 4.2.18 on 2025-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_App', '0003_addblog_image_addblog_time_addblog_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='Image',
            field=models.ImageField(default='', upload_to='Blogs/'),
        ),
    ]
