# Generated by Django 4.2.18 on 2025-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_App', '0004_alter_addblog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
