# Generated by Django 4.2.18 on 2025-02-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto_App', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='Image',
            field=models.ImageField(upload_to='Blogs/'),
        ),
    ]
